In [1]:
# %matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
# import re
import numpy as np

### Importing datasets

In [2]:
results_df = pd.read_csv('Dataset/results.csv')
circuits_df = pd.read_csv('Dataset/circuits.csv')
constructor_results_df = pd.read_csv('Dataset/constructor_results.csv')
constructors_df = pd.read_csv('Dataset/constructors.csv')
drivers_df = pd.read_csv('Dataset/drivers.csv')
races_df = pd.read_csv('Dataset/races.csv')
status_df = pd.read_csv('Dataset/status.csv')

### Datasets relationship and ERM schema

![Data Schema](http://ergast.com/images/ergast_db.png)

### Datasets details:

#### restults: 
- results per race and drivers, points, grid (position at start of race), position at end of race, status of each driver at end of race,....

In [3]:
results_df.head()

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.300,1
1,2,18,2,2,3,5,2,2,2,8.0,58,+5.478,5696094,41,3,1:27.739,217.586,1
2,3,18,3,3,7,7,3,3,3,6.0,58,+8.163,5698779,41,5,1:28.090,216.719,1
3,4,18,4,4,5,11,4,4,4,5.0,58,+17.181,5707797,58,7,1:28.603,215.464,1
4,5,18,5,1,23,3,5,5,5,4.0,58,+18.014,5708630,43,1,1:27.418,218.385,1

#### circuits
- information about race circuits
- circuit id, name, location, latitude...

In [4]:
circuits_df.head()

,circuitId,circuitRef,name,location,country,lat,lng,alt,url
0,1,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.84970,144.96800,10,http://en.wikipedia.org/wiki/Melbourne_Grand_P...
1,2,sepang,Sepang International Circuit,Kuala Lumpur,Malaysia,2.76083,101.73800,18,http://en.wikipedia.org/wiki/Sepang_Internatio...
2,3,bahrain,Bahrain International Circuit,Sakhir,Bahrain,26.03250,50.51060,7,http://en.wikipedia.org/wiki/Bahrain_Internati...
3,4,catalunya,Circuit de Barcelona-Catalunya,Montmeló,Spain,41.57000,2.26111,109,http://en.wikipedia.org/wiki/Circuit_de_Barcel...
4,5,istanbul,Istanbul Park,Istanbul,Turkey,40.95170,29.40500,130,http://en.wikipedia.org/wiki/Istanbul_Park

### constructor_results
- construct results per race: constructor, race, points

In [5]:
constructor_results_df.head()

   constructorResultsId  raceId  constructorId  points status
0                     1      18              1    14.0     \N
1                     2      18              2     8.0     \N
2                     3      18              3     9.0     \N
3                     4      18              4     5.0     \N
4                     5      18              5     2.0     \N

#### constructor
- Information about constructor: id, name, nationality

In [6]:
constructors_df.head()

,constructorId,constructorRef,name,nationality,url
0,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren
1,2,bmw_sauber,BMW Sauber,German,http://en.wikipedia.org/wiki/BMW_Sauber
2,3,williams,Williams,British,http://en.wikipedia.org/wiki/Williams_Grand_Pr...
3,4,renault,Renault,French,http://en.wikipedia.org/wiki/Renault_in_Formul...
4,5,toro_rosso,Toro Rosso,Italian,http://en.wikipedia.org/wiki/Scuderia_Toro_Rosso

#### drivers
- information about drivers: id, name, number, code, date of birth, nationality
- To do later: use age, nationality in performance analysis

In [7]:
drivers_df.head()

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,\N,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,6,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,alonso,14,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,kovalainen,\N,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen

#### races
- Races info: id, year, round of championship, circuit_id, date

In [8]:
races_df.head()

,raceId,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
0,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,09:00:00,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,07:00:00,http://en.wikipedia.org/wiki/2009_Chinese_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,12:00:00,http://en.wikipedia.org/wiki/2009_Bahrain_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,12:00:00,http://en.wikipedia.org/wiki/2009_Spanish_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N

#### status 
- staus id and corresponding race fhich status (accident, disqualified, collision...), each driver at each race is assigned a finish status

In [9]:
status_df.head()

   statusId        status
0         1      Finished
1         2  Disqualified
2         3      Accident
3         4     Collision
4         5        Engine

#### Other datasets for more granular analysis: 
- **constructor_standing**: historical results of constructor standing over races, after each race total points cumulative per constructor
- **drivers_standing**: historical standing of drivers after each race, cumulated sum of obtained points over past races within same season 
- **qualifying**: Qualifying results per driver per race, includes Q1, Q2, Q3 time results and final grid position based on Q3
- **Pit_stops**: pistop information per driver per race (number of the stop, at what lap and its duration)
- **Lap_times**: laptime per race per driver per lap
- **sprint results**: Sprint race results for races with sprint: similar to races in strcuture

### Creating Merged dataset

In [10]:
result_driver = pd.merge(results_df, drivers_df, how='left',on='driverId', suffixes=('_res','_drv'))


result_driver = pd.merge(result_driver, status_df, how='left', on='statusId', suffixes=('_resDrv', '_st'))

result_driver_race = pd.merge(result_driver,races_df,how='left',on='raceId', suffixes=('_resDrv','_rac'))


result_driver_race_circuit = pd.merge(result_driver_race, circuits_df,how='left', on='circuitId', suffixes=('_resDrvRce','_cir'))

merged_df = pd.merge(result_driver_race_circuit, constructors_df,how='left',on='constructorId', suffixes=('_resDrvRceCir','_con'))

In [11]:
pd.set_option('display.max_columns', None)
merged_df.head()

,resultId,raceId,driverId,constructorId,number_res,grid,position,positionText,positionOrder,points,laps,time_resDrv,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId,driverRef,number_drv,code,forename,surname,dob,nationality_resDrvRceCir,url_resDrv,status,year,round,circuitId,name_resDrvRce,date,time_rac,url_rac,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time,circuitRef,name_cir,location,country,lat,lng,alt,url_resDrvRceCir,constructorRef,name,nationality_con,url_con
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.300,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton,Finished,2008,1,1,Australian Grand Prix,2008-03-16,04:30:00,http://en.wikipedia.org/wiki/2008_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.8497,144.968,10,http://en.wikipedia.org/wiki/Melbourne_Grand_P...,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren
1,2,18,2,2,3,5,2,2,2,8.0,58,+5.478,5696094,41,3,1:27.739,217.586,1,heidfeld,\N,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld,Finished,2008,1,1,Australian Grand Prix,2008-03-16,04:30:00,http://en.wikipedia.org/wiki/2008_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.8497,144.968,10,http://en.wikipedia.org/wiki/Melbourne_Grand_P...,bmw_sauber,BMW Sauber,German,http://en.wikipedia.org/wiki/BMW_Sauber
2,3,18,3,3,7,7,3,3,3,6.0,58,+8.163,5698779,41,5,1:28.090,216.719,1,rosberg,6,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg,Finished,2008,1,1,Australian Grand Prix,2008-03-16,04:30:00,http://en.wikipedia.org/wiki/2008_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.8497,144.968,10,http://en.wikipedia.org/wiki/Melbourne_Grand_P...,williams,Williams,British,http://en.wikipedia.org/wiki/Williams_Grand_Pr...
3,4,18,4,4,5,11,4,4,4,5.0,58,+17.181,5707797,58,7,1:28.603,215.464,1,alonso,14,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso,Finished,2008,1,1,Australian Grand Prix,2008-03-16,04:30:00,http://en.wikipedia.org/wiki/2008_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.8497,144.968,10,http://en.wikipedia.org/wiki/Melbourne_Grand_P...,renault,Renault,French,http://en.wikipedia.org/wiki/Renault_in_Formul...
4,5,18,5,1,23,3,5,5,5,4.0,58,+18.014,5708630,43,1,1:27.418,218.385,1,kovalainen,\N,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen,Finished,2008,1,1,Australian Grand Prix,2008-03-16,04:30:00,http://en.wikipedia.org/wiki/2008_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.8497,144.968,10,http://en.wikipedia.org/wiki/Melbourne_Grand_P...,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren

In [12]:
merged_df.columns

Index(['resultId', 'raceId', 'driverId', 'constructorId', 'number_res', 'grid',
       'position', 'positionText', 'positionOrder', 'points', 'laps',
       'time_resDrv', 'milliseconds', 'fastestLap', 'rank', 'fastestLapTime',
       'fastestLapSpeed', 'statusId', 'driverRef', 'number_drv', 'code',
       'forename', 'surname', 'dob', 'nationality_resDrvRceCir', 'url_resDrv',
       'status', 'year', 'round', 'circuitId', 'name_resDrvRce', 'date',
       'time_rac', 'url_rac', 'fp1_date', 'fp1_time', 'fp2_date', 'fp2_time',
       'fp3_date', 'fp3_time', 'quali_date', 'quali_time', 'sprint_date',
       'sprint_time', 'circuitRef', 'name_cir', 'location', 'country', 'lat',
       'lng', 'alt', 'url_resDrvRceCir', 'constructorRef', 'name',
       'nationality_con', 'url_con'],
      dtype='object')

#### Delete unncessary columns:

In [13]:
merged_df = merged_df.drop(columns=['number_res','laps','fastestLap','rank','round',\
                                    'statusId','number_drv','url_resDrv','url_rac',\
                                    'fp1_date', 'fp1_time','fp2_date','fp2_time','fp3_date', 'fp3_time',\
                                    'quali_date','quali_time', 'sprint_date', 'sprint_time',\
                                    'url_resDrvRceCir','url_con'])

In [14]:
pd.set_option('display.max_columns', None)
merged_df.head()

,resultId,raceId,driverId,constructorId,grid,position,positionText,positionOrder,points,time_resDrv,milliseconds,fastestLapTime,fastestLapSpeed,driverRef,code,forename,surname,dob,nationality_resDrvRceCir,status,year,circuitId,name_resDrvRce,date,time_rac,circuitRef,name_cir,location,country,lat,lng,alt,constructorRef,name,nationality_con
0,1,18,1,1,1,1,1,1,10.0,1:34:50.616,5690616,1:27.452,218.300,hamilton,HAM,Lewis,Hamilton,1985-01-07,British,Finished,2008,1,Australian Grand Prix,2008-03-16,04:30:00,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.8497,144.968,10,mclaren,McLaren,British
1,2,18,2,2,5,2,2,2,8.0,+5.478,5696094,1:27.739,217.586,heidfeld,HEI,Nick,Heidfeld,1977-05-10,German,Finished,2008,1,Australian Grand Prix,2008-03-16,04:30:00,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.8497,144.968,10,bmw_sauber,BMW Sauber,German
2,3,18,3,3,7,3,3,3,6.0,+8.163,5698779,1:28.090,216.719,rosberg,ROS,Nico,Rosberg,1985-06-27,German,Finished,2008,1,Australian Grand Prix,2008-03-16,04:30:00,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.8497,144.968,10,williams,Williams,British
3,4,18,4,4,11,4,4,4,5.0,+17.181,5707797,1:28.603,215.464,alonso,ALO,Fernando,Alonso,1981-07-29,Spanish,Finished,2008,1,Australian Grand Prix,2008-03-16,04:30:00,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.8497,144.968,10,renault,Renault,French
4,5,18,5,1,3,5,5,5,4.0,+18.014,5708630,1:27.418,218.385,kovalainen,KOV,Heikki,Kovalainen,1981-10-19,Finnish,Finished,2008,1,Australian Grand Prix,2008-03-16,04:30:00,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.8497,144.968,10,mclaren,McLaren,British

#### Columns Cleaning:

- If position == "\\N", it means that the driver didn't end the race (collision, engine, disqualification...)
- Valid positions are from 1 to 22, we replace "\\N" by 0

In [15]:
merged_df['position'] = merged_df['position'].replace({'\\N':0})
merged_df['position'] = pd.to_numeric(merged_df['position'])

- In status, any status of ending with +x laps, means that the driver ended the race (fishied) but with a delay of x laps from the winner of the race => can change all these status by Finished

In [16]:
merged_df['status'] = merged_df.status.str.replace("\+\d\s\w*|\+\d\d\s\w*", 'Finished')

/var/folders/h0/9p_trgc12md_jlkwc1bs7r480000gn/T/ipykernel_2962/2335551047.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  merged_df['status'] = merged_df.status.str.replace("\+\d\s\w*|\+\d\d\s\w*", 'Finished')

#### Renaming columns

In [17]:
merged_df.columns

Index(['resultId', 'raceId', 'driverId', 'constructorId', 'grid', 'position',
       'positionText', 'positionOrder', 'points', 'time_resDrv',
       'milliseconds', 'fastestLapTime', 'fastestLapSpeed', 'driverRef',
       'code', 'forename', 'surname', 'dob', 'nationality_resDrvRceCir',
       'status', 'year', 'circuitId', 'name_resDrvRce', 'date', 'time_rac',
       'circuitRef', 'name_cir', 'location', 'country', 'lat', 'lng', 'alt',
       'constructorRef', 'name', 'nationality_con'],
      dtype='object')

In [18]:
merged_df.rename(columns={"code": "driverCode", "forename": "driverFirstName","surname": "driverLastName",
                            "dob": "driverDateBirth", "nationality_resDrvRceCir": "driverNationality",
                            "name_resDrvRce":"raceName", "date": "raceDate","time_rac": "timeRace",
                            "name_cir": "circuitName", "name": "constructorName", "nationality_con": "constructtorNationality"
                            }, inplace=True)

In [19]:
merged_df.columns

Index(['resultId', 'raceId', 'driverId', 'constructorId', 'grid', 'position',
       'positionText', 'positionOrder', 'points', 'time_resDrv',
       'milliseconds', 'fastestLapTime', 'fastestLapSpeed', 'driverRef',
       'driverCode', 'driverFirstName', 'driverLastName', 'driverDateBirth',
       'driverNationality', 'status', 'year', 'circuitId', 'raceName',
       'raceDate', 'timeRace', 'circuitRef', 'circuitName', 'location',
       'country', 'lat', 'lng', 'alt', 'constructorRef', 'constructorName',
       'constructtorNationality'],
      dtype='object')

In [27]:
merged_df.to_csv('Dataset/merged_df.csv', index=False)

### Correlations Exploration

In [26]:
corr = merged_df.corr()
corr[abs(corr) < 0.5] = 0
corr

,resultId,raceId,driverId,constructorId,grid,position,positionOrder,points,year,circuitId,lat,lng
resultId,1.000000,0.965235,0.714103,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0
raceId,0.965235,1.000000,0.734566,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0
driverId,0.714103,0.734566,1.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0
constructorId,0.000000,0.000000,0.000000,1.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0
grid,0.000000,0.000000,0.000000,0.0,1.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0
position,0.000000,0.000000,0.000000,0.0,0.0,1.0,0.000000,0.000000,0.0,0.0,0.0,0.0
positionOrder,0.000000,0.000000,0.000000,0.0,0.0,0.0,1.000000,-0.571445,0.0,0.0,0.0,0.0
points,0.000000,0.000000,0.000000,0.0,0.0,0.0,-0.571445,1.000000,0.0,0.0,0.0,0.0
year,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,1.0,0.0,0.0,0.0
circuitId,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,1.0,0.0,0.0
lat,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,1.0,0.0
lng,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,1.0

The only trend (aside from id correlatoins which is negligible) is the insight that positionOrder is negatively correlated with points; this makes complete intuitive sense, and should be considered when modeling going forward. Of the two variables, I would venture to argue that positionOrder is the more relevant of these two for our modeling purposes, though I would like input on this from the members of the team who know F1 better than myself.

### Feature Identification

### Initial visualizations